### ISSUE TITLE
Material 3 upgrade

### ISSUE THREAD

**Issue by alp-well** [SmartToolFactory/Compose-Extended-Gestures#3]
You are using this lib in other libraries like: Compose-Cropper. Compose-Cropper migrated to Material3 but implements this library. So in dependency tree we can see material2 dependency. If you migrate this lib to M3, Compose-Cropper library will be 1 dependency free.

**Comment by SmartToolFactory** [comment]
Material should not be part of gesture library in the first place. It's only needed in app for using Composables like `Text`

**Comment by alp-well** [comment]
Oh, then it's better to get rid of the material library directly. Instead of getting rid of m2 and using m3, it's better to get rid of both m2 and m3 at the same time.

**Comment by SmartToolFactory** [comment]
It's only in app for demos, there is no material in gesture module.

**Comment by alp-well** [comment]
So when we implement this library, we will end up downloading all the libraries that are for the demo app as well. Additionally, the libraries that implement this library will also implement the dependencies of the demo app (like compose cropper). This is unnecessary. Is there a chance to configure the library so that it does not implement the demo app's dependencies?

I mean compose-cropper library implements those extra libs because of the demo app:
```
implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.8.2'
implementation 'androidx.activity:activity-compose:1.9.0'
implementation 'androidx.compose.ui:ui'
implementation "androidx.compose.material:material"
```
