### ISSUE TITLE
How to get the screen size of the element?

### ISSUE THREAD

**Issue by cybercoder-naj** [SmartToolFactory/Compose-Extended-Gestures#4]
I am working on the Canvas object such as follows:

```kotlin
fun Component() {
  Canvas(
    modifier = Modifier
      .clipToBounds()
      .pointerMotionEvents(
        onDown = {/* I want the size of the Canvas here */}
      )
  ) {
    /* drawing elements on the Canvas */
  }
}
```

Do you think adding something to the modifier with the size of the Canvas would be possible? If the user is pressing "Down" on the canvas, it is useful to know where it is with respect to the dimensions of the canvas.

**Comment by cybercoder-naj** [comment]
The current workaround is having a local state to keep the size. Wondering if the library can do this without it.

```kt
@Composable
fun Component() {
  var canvasSize by remember { mutableStateOf(Size.Unspecified) }

  Canvas(
    modifier = Modifier
      /* look previous comment */
  ) {
    canvasSize = size

    /* drawing elements */
  }
}
```

**Comment by SmartToolFactory** [comment]
Good catch. I will add pointerEventScope functions which can be used inside `pointerInputEvent`

**Comment by SmartToolFactory** [comment]
you can use PointerInputScope function for this as

```
Modifier.pointerInput(Unit){
    val size = size
    detectMotionEvents(
        onDown = {
            
        },
        onMove = {
            
        },
        onUp = {
            
        }
    )
}
```
